---
abstract: 'Instantiate a Metabase backend for CPAN Testers '
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101040'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Metabase
no_index:
  directory:
    - t
    - xt
    - examples
recommends: {}
requires:
  File::Find: 0
  File::Spec: 3.31
  File::Temp: 0.20
  Metabase::Archive::S3: 0.009
  Metabase::Archive::SQLite: 0.009
  Metabase::Index::FlatFile: 0.009
  Metabase::Index::SimpleDB: 0.009
  Metabase::Librarian: 0.009
  Moose: 0.93
  Net::Amazon::Config: 0.001
  Path::Class: 0.17
  Test::More: 0.88
  namespace::autoclean: 0.09
  perl: 5.006
resources:
  repository: http://github.com/dagolden/cpan-testers-metabase
version: 1.999001
