---
abstract: 'Instantiate a Metabase backend for CPAN Testers '
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Metabase
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Testers::Metabase:
    file: lib/CPAN/Testers/Metabase.pm
    version: 1.999002
  CPAN::Testers::Metabase::Demo:
    file: lib/CPAN/Testers/Metabase/Demo.pm
    version: 1.999002
requires:
  File::Temp: 0
  Metabase::Archive::SQLite: 1.000
  Metabase::Gateway: 0
  Metabase::Index::FlatFile: 1.000
  Metabase::Librarian: 1.000
  Moose: 0
  Path::Class: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Metabase
  homepage: https://github.com/dagolden/cpan-testers-metabase
  repository: https://github.com/dagolden/cpan-testers-metabase.git
version: 1.999002
